# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kyle Zimmerman's
email: zimmerkyle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  **I'm a Programmer, Developer and Problem-Solver.** I love to solve puzzles, tinker, and code.

  I've work as a Web Developer at [Conestoga College](http://www.conestogac.on.ca) since 2014 and I graduate in April 2016.

  **If you're looking for a talented, hard working developer** [let me know](mailto:zimmerkyle@gmail.com). You can also check out my [resume](/resume/), [projects](/projects/), and [skills](/skills/).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kylezimmerman.github.io" # the base hostname & protocol for your site
github_username:  kylezimmerman

# Build settings
markdown: kramdown
